### 다중 선형 회귀 구현

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [8]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])


In [5]:
model = nn.Linear(3, 1) # parameter = input * output + 1
list(model.parameters())

[Parameter containing:
 tensor([[0.1235, 0.4542, 0.2529]], requires_grad=True),
 Parameter containing:
 tensor([0.3683], requires_grad=True)]

In [9]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 10155.487305
Epoch  100/2000 Cost: 4.104310
Epoch  200/2000 Cost: 3.902786
Epoch  300/2000 Cost: 3.711903
Epoch  400/2000 Cost: 3.531047
Epoch  500/2000 Cost: 3.359678
Epoch  600/2000 Cost: 3.197345
Epoch  700/2000 Cost: 3.043531
Epoch  800/2000 Cost: 2.897783
Epoch  900/2000 Cost: 2.759721
Epoch 1000/2000 Cost: 2.628906
Epoch 1100/2000 Cost: 2.504957
Epoch 1200/2000 Cost: 2.387514
Epoch 1300/2000 Cost: 2.276219
Epoch 1400/2000 Cost: 2.170786
Epoch 1500/2000 Cost: 2.070873
Epoch 1600/2000 Cost: 1.976200
Epoch 1700/2000 Cost: 1.886492
Epoch 1800/2000 Cost: 1.801479
Epoch 1900/2000 Cost: 1.720954
Epoch 2000/2000 Cost: 1.644615


In [10]:
new_x = torch.FloatTensor([73, 80, 75])
new_y = model(new_x)

print(list(model.parameters()))
print(new_y)

[Parameter containing:
tensor([[0.6632, 0.6727, 0.6707]], requires_grad=True), Parameter containing:
tensor([0.3759], requires_grad=True)]
tensor([152.9006], grad_fn=<ViewBackward0>)


### Subclss 모델

In [35]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(3, 3)
        self.linear2 = nn.Linear(3, 1)
        self.relu = nn.ReLU()


    def forward(self, x):
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        return x

In [46]:
model = LinearRegressionModel()

In [47]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1653,  0.0677, -0.1082],
         [-0.0610, -0.2678,  0.2563],
         [ 0.1100,  0.1759, -0.0555]], requires_grad=True),
 Parameter containing:
 tensor([-0.0513,  0.0448,  0.2842], requires_grad=True),
 Parameter containing:
 tensor([[ 0.0901, -0.2698, -0.2470]], requires_grad=True),
 Parameter containing:
 tensor([0.0374], requires_grad=True)]

In [48]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [49]:
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

In [50]:
epochs = 1000

for epoch in range(epochs + 1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, epochs, cost.item()
      ))

Epoch    0/1000 Cost: 31029.718750
Epoch  100/1000 Cost: 26822.599609
Epoch  200/1000 Cost: 21198.099609
Epoch  300/1000 Cost: 13778.745117
Epoch  400/1000 Cost: 7009.512695
Epoch  500/1000 Cost: 2628.088379
Epoch  600/1000 Cost: 689.411499
Epoch  700/1000 Cost: 125.598778
Epoch  800/1000 Cost: 17.224161
Epoch  900/1000 Cost: 2.736799
Epoch 1000/1000 Cost: 1.313214
