In [2]:
import torch

print(torch.__version__)

2.4.0


In [3]:
torch.cuda.is_available()

True

## 텐서 조작하기

### 1. 벡터, 행렬, 텐서

#### 1) 벡터, 행렬, 텐서 이해하기

- 데이터가 행렬로 표현돼 있으면 벡터, 행렬, 텐서 라는 표현을 사용한다.
    - 1차원 벡터, 2차원 행렬, 3차원 텐서
- 스칼라는 차원이 없는 값

※ 한번에 처리할 수 있는 데이터 양 => **배치**
- 배치까지 고려하면 GPU에 들어가는 데이터 차원은 + 1

#### 2) PyTorch Tensor Shape Convention

### 3. 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

#### 1) 1D with PyTorch

In [4]:
t =  torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim()) # 차원 숫자 / rank

1


torch.Size([7])

In [ ]:
t.shape # attribute
t.size() # method

In [7]:
print(t[0], t[1], t[-1])

tensor(0.) tensor(1.) tensor(6.)


In [8]:
print(t[2:5], t[4:-1])

tensor([2., 3., 4.]) tensor([4., 5.])


#### 2) 2D with PyTorch

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [13]:
print(t[2, 1])
print(t[2])
print(t[: ,2])

tensor(8.)
tensor([7., 8., 9.])
tensor([ 3.,  6.,  9., 12.])


#### 4) 최대(Max)와 아그맥스(ArgMax)

In [14]:
t = torch.FloatTensor([[1., 2.], [3., 4.]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [15]:
t.max()

tensor(4.)

In [19]:
t.max(dim=0)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

In [24]:
# 10개 사물 분류 모델
result = torch.FloatTensor([0.1, 0.05, 0.5, 0.1, 0.1, 0.01, 0.01, 0.01, 0.01 ,0.87])
names = ['cat', 'dog', 'lion', 'tiger', 'wolf', 'fox', 'snake', 'rabbit', 'horse', 'zebra']
names[result.argmax()]

'zebra'

#### 5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경

In [25]:
import numpy as np

t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
ft.shape

torch.Size([2, 2, 3])

In [27]:
reshaped_ft = ft.view([3, 4])
print(reshaped_ft)
reshaped_ft.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


torch.Size([3, 4])

In [28]:
reshaped_ft = ft.view([4, 3])
print(reshaped_ft)
reshaped_ft.shape

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


torch.Size([4, 3])

In [31]:
reshaped_ft = ft.view([3, -1]) # -1 은 알아서 해
print(reshaped_ft)
reshaped_ft.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


torch.Size([3, 4])

In [32]:
reshaped_ft = ft.view([4, 3, 1])
print(reshaped_ft)
reshaped_ft.shape

tensor([[[ 0.],
         [ 1.],
         [ 2.]],

        [[ 3.],
         [ 4.],
         [ 5.]],

        [[ 6.],
         [ 7.],
         [ 8.]],

        [[ 9.],
         [10.],
         [11.]]])


torch.Size([4, 3, 1])

In [33]:
reshaped_ft = ft.view([2, 2, 1, 3])
print(reshaped_ft)
reshaped_ft.shape

tensor([[[[ 0.,  1.,  2.]],

         [[ 3.,  4.,  5.]]],


        [[[ 6.,  7.,  8.]],

         [[ 9., 10., 11.]]]])


torch.Size([2, 2, 1, 3])

In [34]:
t = np.ones([128, 128])
tf = torch.FloatTensor(t)
tf.shape

torch.Size([128, 128])

In [36]:
tf.view([128, 128, 1])
tf.shape

torch.Size([128, 128])

In [37]:
tf.squeeze() # 차원하나 없애는 거
tf.shape

torch.Size([128, 128])

In [38]:
tf = tf.view([-1, 1])
tf.shape

torch.Size([16384, 1])

In [43]:
tf = tf.view([128, 1, 128])
tf.shap

torch.Size([128, 1, 128])

In [44]:
tf = tf.squeeze() ## 사이즈 어디가 1이든지 다 지워주나? 다지워주넹
tf.shape

torch.Size([128, 128])

In [41]:
tf = tf.unsqueeze(0)
tf.shape

torch.Size([1, 16384])